# Generated by Django 2.2.5 on 2019-09-19 02:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('login', '0002_remove_profile_user_course'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='user_course',
            field=models.CharField(choices=[('BD', 'Banco de dados'), ('ADS', 'Analise e desenvolvimento de sistemas')], default='ADS', max_length=5),
        ),
    ]
